version: "3"

vars:
  PROTO_DIR: proto
  BUILD_OUTPUT: build
  BINARY_NAME: zera

tasks:
  # ==================== Ent 代码生成 ====================
  ent:gen:
    desc: "生成 Ent ORM 代码"
    dir: backend
    cmds:
      - go generate ./ent
    sources:
      - ent/schema/*.go
    generates:
      - ent/*.go
      - ent/**/*.go

  # ==================== Proto 代码生成 ====================
  proto:gen:
    desc: "生成所有 proto 代码（前端 + 后端并行）"
    deps:
      - proto:gen:backend
      - proto:gen:frontend

  proto:gen:backend:
    desc: "生成后端 Go 代码"
    dir: backend
    cmds:
      - buf generate
    sources:
      - ../proto/**/*.proto
      - buf.gen.yaml
    generates:
      - gen/**/*.go

  proto:gen:frontend:
    desc: "生成前端 TypeScript 代码"
    dir: frontend
    cmds:
      - buf generate
    sources:
      - ../proto/**/*.proto
      - buf.gen.yaml
    generates:
      - src/gen/**/*.ts

  # ==================== 构建 ====================
  build:
    desc: "完整构建: 前端打包 -> 嵌入静态资源 -> 后端编译"
    cmds:
      - task: build:clean
      - task: proto:gen
      - task: build:frontend
      - task: build:embed
      - task: build:backend
      - task: build:cli
      - task: build:clean:static
      - echo "✅ 构建完成! 输出目录 {{.BUILD_OUTPUT}}/"

  build:clean:
    desc: "清理构建产物"
    cmds:
      - cmd /c "if exist {{.BUILD_OUTPUT}} rmdir /s /q {{.BUILD_OUTPUT}}"
      - cmd /c "if exist backend\\internal\\static\\dist rmdir /s /q backend\\internal\\static\\dist"
      - cmd /c "mkdir {{.BUILD_OUTPUT}}"

  build:clean:static:
    desc: "清理静态资源目录(保留.gitkeep)"
    cmds:
      - task: build:clean:static:{{OS}}

  build:clean:static:windows:
    internal: true
    cmds:
      - cmd /c "for /d %i in (backend\internal\static\dist\*) do rmdir /s /q %i"
      - cmd /c "for %i in (backend\internal\static\dist\*) do if not %~nxi==.gitkeep del /q %i"
      - cmd /c "if not exist backend\internal\static\dist\.gitkeep type nul > backend\internal\static\dist\.gitkeep"

  build:clean:static:linux:
    internal: true
    cmds:
      - find backend/internal/static/dist -mindepth 1 ! -name '.gitkeep' -exec rm -rf {} + 2>/dev/null || true
      - touch backend/internal/static/dist/.gitkeep

  build:clean:static:darwin:
    internal: true
    cmds:
      - find backend/internal/static/dist -mindepth 1 ! -name '.gitkeep' -exec rm -rf {} + 2>/dev/null || true
      - touch backend/internal/static/dist/.gitkeep

  build:frontend:
    desc: "构建前端"
    dir: frontend
    cmds:
      - bun run build
    sources:
      - src/**/*
      - index.html
      - vite.config.ts
      - tsconfig*.json
    generates:
      - dist/**/*

  build:embed:
    desc: "将前端产物复制到后端嵌入目录"
    cmds:
      - cmd /c "if exist backend\\internal\\static\\dist rmdir /s /q backend\\internal\\static\\dist"
      - cmd /c "xcopy /E /I /Y frontend\\dist backend\\internal\\static\\dist"
    sources:
      - frontend/dist/**/*
    generates:
      - backend/internal/static/dist/**/*

  build:backend:
    desc: "构建后端（包含嵌入的静态资源）"
    dir: backend
    cmds:
      - go build -ldflags="-s -w" -o ../{{.BUILD_OUTPUT}}/{{.BINARY_NAME}}.exe ./cmd/server
    sources:
      - "**/*.go"
      - internal/static/dist/**/*
    generates:
      - ../{{.BUILD_OUTPUT}}/{{.BINARY_NAME}}.exe

  build:cli:
    desc: "构建 zera CLI（输出到项目根目录）"
    dir: backend
    cmds:
      - go build -ldflags="-s -w" -o ../zera.exe ./cmd/zera
    sources:
      - "**/*.go"
    generates:
      - ../zera.exe
